pipeline {
    agent any
    tools { 
        maven 'Maven 3.6.1'
        jdk 'jdk8' 
    }
    stages {
        stage ('Initialize') {
           steps {
               bat '''
                   echo "PATH = ${PATH}"
                   echo "MAVEN_HOME = ${MAVEN_HOME}"
              '''
       		}
		}
        stage('Build') {
            steps {
                echo 'Building..'
                bat '''
                	cd rss-service
                	mvn clean install
                '''
 	       }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}