pipeline {
    agent any
    tools { 
        maven 'Maven 3.6.1'
        jdk 'jdk8' 
    }
    stages {
        stage ('Initialize') {
           steps {
               bat '''
                   echo "PATH = ${PATH}"
                   echo "MAVEN_HOME = ${MAVEN_HOME}"
              '''
       		}
		}
        stage('Build') {
            steps {
               	echo 'Building'
               	bat 'cd rss-service'
				stages {
                	stage('Clean') {
            			steps {			                
			                bat	'mvn clean'
            			}
            		}
					stage('Compile') {
            			steps {			                
			                bat	'mvn compile'
            			}
            		}
               		stage('Docker Image') {
            			steps {			                
			                bat	'mvn install -DskipTests'
            			}
            		}
               }
 	       }
        }
        stage('Test') {
            steps {
                echo 'Testing'
                bat '''
                	cd rss-service
                	mvn test
                '''
            }
        }
        stage('Run') {
            steps {
                echo 'Runnnig'
                docker.image("kpayares/rss-service:latest").run('-p 8180:8180 --name rss-service')
            }
        }
    }
}