pipeline {
    agent any
    tools { 
        maven 'Maven 3.6.1'
        jdk 'jdk8' 
    }
    stages {
        stage ('Initialize') {
           steps {
               bat '''
                   echo "PATH = ${PATH}"
                   echo "MAVEN_HOME = ${MAVEN_HOME}"
              '''
       		}
		}
        stage('Build') {
            steps {
               	echo 'Building'
               	bat 'cd rss-service'
				echo 'Cleaning'			                
			    bat	'mvn clean'		
				echo 'Compiling'		                
				bat	'mvn compile'	
               	echo 'Image'		                
				bat	'mvn install -DskipTests'	
 	       }
        }
        stage('Test') {
            steps {
                echo 'Testing'
                bat '''
                	cd rss-service
                	mvn test
                '''
            }
        }
        stage('Run') {
            steps {
                echo 'Runnnig'
                bat 'docker run -p 8180:8180 --name rss-service kpayares/rss-service:latest'
            }
        }
    }
}